CREATE TABLE department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE employee (
    id UUID PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    position VARCHAR(255),
    salary DECIMAL(10,2),
    department_id BIGINT,
    CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department(id)
);
