CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    locked BOOLEAN DEFAULT FALSE
);

INSERT INTO department (name) VALUES ('IT');
INSERT INTO department (name) VALUES ('HR');

INSERT INTO employee (id, first_name, last_name, position, salary, department_id) VALUES
    (random_uuid(), 'Alice', 'Smith', 'Developer', 80000, 1),
    (random_uuid(), 'Bob', 'Johnson', 'Tester', 65000, 1),
    (random_uuid(), 'Carol', 'Williams', 'SysAdmin', 75000, 1),
    (random_uuid(), 'David', 'Brown', 'HR Specialist', 60000, 2),
    (random_uuid(), 'Eve', 'Davis', 'Recruiter', 62000, 2),
    (random_uuid(), 'Frank', 'Miller', 'IT Analyst', 70000, 1),
    (random_uuid(), 'Grace', 'Wilson', 'HR Analyst', 63000, 2);

-- пароли юзеров 12345
INSERT INTO users (id, username, password, role, locked) VALUES
    (1, 'VelikiAdmin', '$2a$10$0PkKFHllUlY/CYJQemSptOh0i2I1/opAsiLNwZAXFjmbCSZVmB8re', 'SUPER_ADMIN', false),
    (2, 'VelikiModerator', '$2a$10$0PkKFHllUlY/CYJQemSptOh0i2I1/opAsiLNwZAXFjmbCSZVmB8re', 'MODERATOR', false),
    (3, 'ProstoUser', '$2a$10$0PkKFHllUlY/CYJQemSptOh0i2I1/opAsiLNwZAXFjmbCSZVmB8re', 'USER', false);
